### ISSUE TITLE
@clayui/css: Build is broken on Node 12

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2298]
Console throws this error:
```log
lerna ERR! yarn run build exited 1 in '@clayui/css'
lerna ERR! yarn run build stdout:
$ yarn compile
$ gulp compile
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/diegonascimento/workspace/clay/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/diegonascimento/workspace/clay/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/diegonascimento/workspace/clay/node_modules/gulp/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
error Command failed with exit code 1.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@clayui/css'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Probably the root cause is here: https://github.com/gulpjs/gulp/issues/2324 😢

**Comment by matuzalemsteles** [comment]
duplicate #2053
