### ISSUE TITLE
The compilation process clayui.com is broken

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/clay#741]
The clayui.com build process is broken. But it was necessary to regenerate `yarn.lock` to be able to work again, updating some dependencies.

```
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/liferay/Clay/clay/node_modules/gulp-sass/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:924:18)
    at Object.getInstalledBinaries (/Users/liferay/Clay/clay/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/Users/liferay/Clay/clay/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/liferay/Clay/clay/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/liferay/Clay/clay/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/liferay/Clay/clay/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/liferay/Clay/clay/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
```

**Comment by matuzalemsteles** [comment]
Done https://github.com/liferay/clay/pull/744/commits/8cd764413b9f3a9154f999b3606aefbd70c26762#diff-8ee2343978836a779dc9f8d6b794c3b2
